spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
    loadbalancer:
      ribbon:
        enabled: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: websocket-car-entry
          uri: http://car-entry-control/
          predicates:
            - Path=/gs-guide-websocket/**
#    routes:
#      - id: device-registration-core
#        uri: lb://device-registration-core
#        predicates:
#          - Path=/device-registration-core/**
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761
#
server:
  port: 8081
#
logging:
  level:
    org.springframework: TRACE
#
#management:
#  endpoint:
#    gateway:
#      enabled: true

#spring:
#  main:
#    web-application-type: reactive
#  application:
#    name: ariss-gateway-proxy
#    loadbalancer:
#      ribbon:
#        enabled: false
#
#  cloud:
#    gateway:
#      routes:
#      - id: device-registration-core
#        uri: lb://device-registration-core
#        predicates:
#          - Path=/device-registration-core/**